USE [master]
GO
/****** Object:  Database [PERSONAL]    Script Date: 20/08/2020 11:28:43 ******/
CREATE DATABASE [PERSONAL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PERSONAL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PERSONAL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PERSONAL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PERSONAL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PERSONAL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PERSONAL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PERSONAL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PERSONAL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PERSONAL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PERSONAL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PERSONAL] SET ARITHABORT OFF 
GO
ALTER DATABASE [PERSONAL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PERSONAL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PERSONAL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PERSONAL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PERSONAL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PERSONAL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PERSONAL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PERSONAL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PERSONAL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PERSONAL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PERSONAL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PERSONAL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PERSONAL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PERSONAL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PERSONAL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PERSONAL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PERSONAL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PERSONAL] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PERSONAL] SET  MULTI_USER 
GO
ALTER DATABASE [PERSONAL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PERSONAL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PERSONAL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PERSONAL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PERSONAL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PERSONAL] SET QUERY_STORE = OFF
GO
USE [PERSONAL]
GO
/****** Object:  User [del]    Script Date: 20/08/2020 11:28:44 ******/
CREATE USER [del] FOR LOGIN [del] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  User [dedo]    Script Date: 20/08/2020 11:28:44 ******/
CREATE USER [dedo] FOR LOGIN [dedo] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [del]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [del]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [del]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [del]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [del]
GO
ALTER ROLE [db_datareader] ADD MEMBER [del]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [del]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [del]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [del]
GO
ALTER ROLE [db_owner] ADD MEMBER [dedo]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [dedo]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [dedo]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [dedo]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [dedo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [dedo]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [dedo]
GO
ALTER ROLE [db_denydatareader] ADD MEMBER [dedo]
GO
ALTER ROLE [db_denydatawriter] ADD MEMBER [dedo]
GO
/****** Object:  Table [dbo].[CLIENTES]    Script Date: 20/08/2020 11:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTES](
	[ID_CLIENTE] [int] NULL,
	[NOMBRE] [nvarchar](100) NULL,
	[SEXO] [nchar](1) NULL,
	[EDAD] [int] NULL,
	[OBSERVACIONES] [nvarchar](100) NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_BUSCAR_CLIENTE]    Script Date: 20/08/2020 11:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_BUSCAR_CLIENTE]
 @ID_CLIENTE INTEGER

 AS
 BEGIN
 SELECT NOMBRE,SEXO,EDAD,OBSERVACIONES FROM CLIENTES  WHERE ID_CLIENTE=@ID_CLIENTE
 END

GO
/****** Object:  StoredProcedure [dbo].[SP_ELIMINAR_CLIENTE]    Script Date: 20/08/2020 11:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_ELIMINAR_CLIENTE]
 @ID_CLIENTE INTEGER
 

 AS
 BEGIN
 DELETE FROM CLIENTES WHERE ID_CLIENTE=@ID_CLIENTE
 END

GO
/****** Object:  StoredProcedure [dbo].[SP_INSERTAR_CLIENTE]    Script Date: 20/08/2020 11:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INSERTAR_CLIENTE]
 @ID_CLIENTE INTEGER,
 @NOMBRE NVARCHAR(100),
 @SEXO NCHAR(1),
 @EDAD INTEGER,
 @OBSERVACIONES NVARCHAR(100)

 AS
 BEGIN
 INSERT CLIENTES (ID_CLIENTE,NOMBRE,SEXO,EDAD,OBSERVACIONES) VALUES (@ID_CLIENTE,@NOMBRE,@SEXO,@EDAD,@OBSERVACIONES)
 END

GO
/****** Object:  StoredProcedure [dbo].[SP_MODIFICAR_CLIENTE]    Script Date: 20/08/2020 11:28:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_MODIFICAR_CLIENTE]
 @ID_CLIENTE INTEGER,
 @NOMBRE NVARCHAR(100),
 @SEXO NCHAR(1),
 @EDAD INTEGER,
 @OBSERVACIONES NVARCHAR(100)

 AS
 BEGIN
 UPDATE CLIENTES SET NOMBRE = @NOMBRE,SEXO=@SEXO,EDAD=@EDAD,OBSERVACIONES=@OBSERVACIONES WHERE ID_CLIENTE=@ID_CLIENTE
 END

GO
USE [master]
GO
ALTER DATABASE [PERSONAL] SET  READ_WRITE 
GO
