CREATE PROCEDURE SP_INSERTAR_CLIENTE
 @ID_CLIENTE INTEGER,
 @NOMBRE NVARCHAR(100),
 @SEXO NCHAR(1),
 @EDAD INTEGER,
 @OBSERVACIONES NVARCHAR(100)

 AS
 BEGIN
 INSERT CLIENTES (ID_CLIENTE,NOMBRE,SEXO,EDAD,OBSERVACIONES) VALUES (@ID_CLIENTE,@NOMBRE,@SEXO,@EDAD,@OBSERVACIONES)
 END

